spring:
    application:
        name: 06_SpringSecurity_OAuth2.0_App
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: Ov23liDHqAD11JCdDKXr
                        clientSecret: 30a1e8ec7a74169c5aa37df4367eb547e33a6914